-- Insert 50 Famous World Sites
INSERT INTO sites (name, description, location, crowd_level) VALUES
('Eiffel Tower', 'Wrought-iron lattice tower on the Champ de Mars in Paris, France.', '{"lat": 48.8584, "lng": 2.2945}', 'high'),
('Statue of Liberty', 'Colossal neoclassical sculpture on Liberty Island in New York Harbor.', '{"lat": 40.6892, "lng": -74.0445}', 'moderate'),
('Great Wall of China', 'Series of fortifications made of stone, brick, tamped earth, wood, and other materials.', '{"lat": 40.4319, "lng": 116.5704}', 'high'),
('Taj Mahal', 'Ivory-white marble mausoleum on the right bank of the river Yamuna in Agra, India.', '{"lat": 27.1751, "lng": 78.0421}', 'high'),
('Machu Picchu', '15th-century Inca citadel, located in the Eastern Cordillera of southern Peru.', '{"lat": -13.1631, "lng": -72.5450}', 'moderate'),
('Colosseum', 'Oval amphitheatre in the centre of the city of Rome, Italy.', '{"lat": 41.8902, "lng": 12.4922}', 'high'),
('Christ the Redeemer', 'Art Deco statue of Jesus Christ in Rio de Janeiro, Brazil.', '{"lat": -22.9519, "lng": -43.2105}', 'moderate'),
('Petra', 'Historical and archaeological city in southern Jordan.', '{"lat": 30.3285, "lng": 35.4444}', 'moderate'),
('Pyramids of Giza', 'Archaeological site on the Giza Plateau, on the outskirts of Cairo, Egypt.', '{"lat": 29.9792, "lng": 31.1342}', 'high'),
('Sydney Opera House', 'Multi-venue performing arts centre at Sydney Harbour in Sydney, Australia.', '{"lat": -33.8568, "lng": 151.2153}', 'moderate'),
('Burj Khalifa', 'Skyscraper in Dubai, United Arab Emirates, the world''s tallest building.', '{"lat": 25.1972, "lng": 55.2744}', 'high'),
('Santorini', 'Island in the southern Aegean Sea, about 200 km southeast of Greece''s mainland.', '{"lat": 36.3932, "lng": 25.4615}', 'high'),
('Grand Canyon', 'Steep-sided canyon carved by the Colorado River in Arizona, United States.', '{"lat": 36.1069, "lng": -112.1129}', 'moderate'),
('Mount Fuji', 'Active volcano about 100 kilometers southwest of Tokyo, Japan.', '{"lat": 35.3606, "lng": 138.7274}', 'low'),
('Stonehenge', 'Prehistoric monument in Wiltshire, England.', '{"lat": 51.1789, "lng": -1.8262}', 'moderate'),
('Niagara Falls', 'Group of three waterfalls at the southern end of Niagara Gorge.', '{"lat": 43.0962, "lng": -79.0377}', 'high'),
('Acropolis of Athens', 'Ancient citadel located on a rocky outcrop above the city of Athens.', '{"lat": 37.9715, "lng": 23.7257}', 'high'),
('Louvre Museum', 'The world''s largest art museum and a historic monument in Paris, France.', '{"lat": 48.8606, "lng": 2.3376}', 'high'),
('Central Park', 'Urban park in New York City, between the Upper West Side and the Upper East Side.', '{"lat": 40.785091, "lng": -73.968285}', 'moderate'),
('Times Square', 'Major commercial intersection, tourist destination, entertainment center, and neighborhood in Midtown Manhattan.', '{"lat": 40.7580, "lng": -73.9855}', 'high'),
('Disneyland Park', 'Theme park at the Disneyland Resort in Anaheim, California.', '{"lat": 33.8121, "lng": -117.9190}', 'high'),
('Golden Gate Bridge', 'Suspension bridge spanning the Golden Gate, the one-mile-wide strait connecting San Francisco Bay and the Pacific Ocean.', '{"lat": 37.8199, "lng": -122.4783}', 'moderate'),
('Buckingham Palace', 'London residence and administrative headquarters of the monarch of the United Kingdom.', '{"lat": 51.5014, "lng": -0.1419}', 'high'),
('Vatican Museums', 'Public art and sculpture museums in the Vatican City.', '{"lat": 41.9067, "lng": 12.4536}', 'high'),
('Blue Mosque', 'Historic mosque located in Istanbul, Turkey.', '{"lat": 41.0054, "lng": 28.9768}', 'moderate'),
('Angkor Wat', 'Temple complex in Cambodia and the largest religious monument in the world.', '{"lat": 13.4125, "lng": 103.8670}', 'moderate'),
('Forbidden City', 'Palace complex in central Beijing, China.', '{"lat": 39.9163, "lng": 116.3972}', 'high'),
('Mount Everest', 'Earth''s highest mountain above sea level, located in the Mahalangur Himal sub-range of the Himalayas.', '{"lat": 27.9881, "lng": 86.9250}', 'low'),
('Victoria Falls', 'Waterfall in southern Africa on the Zambezi River at the border between Zambia and Zimbabwe.', '{"lat": -17.9243, "lng": 25.8572}', 'moderate'),
('Banff National Park', 'Canada''s oldest national park, located in the Rocky Mountains.', '{"lat": 51.4968, "lng": -115.9281}', 'low'),
('Yellowstone National Park', 'American national park located in the western United States.', '{"lat": 44.4280, "lng": -110.5885}', 'moderate'),
('Galapagos Islands', 'Archipelago of volcanic islands in the Pacific Ocean.', '{"lat": -0.8293, "lng": -91.1358}', 'low'),
('Serengeti National Park', 'Tanzanian national park in the Serengeti ecosystem in the Mara and Simiyu regions.', '{"lat": -2.1540, "lng": 34.6857}', 'low'),
('Iguazu Falls', 'Waterfalls of the Iguazu River on the border of the Argentine province of Misiones and the Brazilian state of Paraná.', '{"lat": -25.6953, "lng": -54.4367}', 'moderate'),
('Ha Long Bay', 'UNESCO World Heritage Site and popular travel destination in Quang Ninh Province, Vietnam.', '{"lat": 20.9101, "lng": 107.1839}', 'moderate'),
('Cinque Terre', 'Rugged portion of coast on the Italian Riviera.', '{"lat": 44.1461, "lng": 9.6439}', 'high'),
('Neuschwanstein Castle', '19th-century historicist palace on a rugged hill above the village of Hohenschwangau in southwest Bavaria, Germany.', '{"lat": 47.5576, "lng": 10.7498}', 'high'),
('Sagrada Familia', 'Large unfinished minor basilica in the Eixample district of Barcelona, Catalonia, Spain.', '{"lat": 41.4036, "lng": 2.1744}', 'high'),
('Alhambra', 'Palace and fortress complex located in Granada, Andalusia, Spain.', '{"lat": 37.1760, "lng": -3.5875}', 'moderate'),
('Table Mountain', 'Flat-topped mountain forming a prominent landmark overlooking the city of Cape Town in South Africa.', '{"lat": -33.9628, "lng": 18.4098}', 'moderate'),
('Chichen Itza', 'Large pre-Columbian city built by the Maya people of the Terminal Classic period.', '{"lat": 20.6843, "lng": -88.5678}', 'high'),
('Tulum', 'Site of a pre-Columbian Mayan walled city serving as a major port for Coba.', '{"lat": 20.2114, "lng": -87.4654}', 'high'),
('Bora Bora', 'Island group in the Leeward Islands.', '{"lat": -16.5004, "lng": -151.7415}', 'low'),
('Maldives', 'Archipelagic country in the Indian subcontinent of Asia, situated in the Indian Ocean.', '{"lat": 3.2028, "lng": 73.2207}', 'moderate'),
('Kyoto Imperial Palace', 'Former ruling palace of the Emperor of Japan.', '{"lat": 35.0254, "lng": 135.7621}', 'moderate'),
('Fushimi Inari-taisha', 'Head shrine of the kami Inari, located in Fushimi-ku, Kyoto, Japan.', '{"lat": 34.9671, "lng": 135.7727}', 'high'),
('Marina Bay Sands', 'Integrated resort fronting Marina Bay in Singapore.', '{"lat": 1.2834, "lng": 103.8607}', 'high'),
('Gardens by the Bay', 'Nature park spanning 101 hectares in the Central Region of Singapore.', '{"lat": 1.2816, "lng": 103.8636}', 'moderate'),
('Petronas Towers', 'Twin skyscrapers in Kuala Lumpur, Malaysia.', '{"lat": 3.1579, "lng": 101.7123}', 'high'),
('Bali', 'Province of Indonesia and the westernmost of the Lesser Sunda Islands.', '{"lat": -8.3405, "lng": 115.0920}', 'high');
